const {chromium}=require('C:/Users/Asus/AppData/Local/npm-cache/_npx/420ff84f11983ee5/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),results=[],errors=[];let reads=0;
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+path.sep))return res.writeHead(403).end();try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000},hasTouch:true});page.setDefaultTimeout(15000);
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push({message:m.text(),source:m.location().url});});
 page.on('request',r=>{if(r.url().includes('/rest/v1/')){assert.equal(r.method(),'GET');if(new URL(r.url()).pathname.endsWith('/properties'))reads++;}});
 const check=async(name,fn)=>{try{const detail=await fn();results.push({name,result:'PASS',detail});console.log('PASS '+name);}catch(e){results.push({name,result:'FAIL',error:e.message});console.log('FAIL '+name+': '+e.message);}};
 const visit=async(q='')=>{await page.goto(base+'/listings.html'+q,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>publicState.listingsLoaded,null,{timeout:45000});await page.waitForSelector('#listingMapHolder svg',{state:'attached'});};
 const select=(id,v)=>page.locator('#'+id).selectOption(v);
 const open=async(id)=>{if(!await page.locator('#'+id).isVisible())await page.locator('[aria-controls="'+id+'"]').click();};
 const count=()=>page.evaluate(()=>filteredListings().length);
 const sync=async(slug)=>{assert.equal(await page.locator('#listingProvinceFilter').inputValue(),slug);assert.equal(new URL(page.url()).searchParams.get('province'),slug==='all'?null:slug);assert.deepEqual(await page.locator('#listingMapHolder [aria-pressed="true"]').evaluateAll(n=>n.map(p=>p.dataset.province)),slug==='all'?[]:[slug]);assert.match(await page.locator('#listingsCount').innerText(),new RegExp('^'+await count()+' propert'));};
 const screenshot=async(name)=>{await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('#listingsGrid img')].map(i=>{i.loading='eager';return i.decode().catch(()=>{});}));document.querySelector('.listings-section').scrollIntoView({behavior:'instant'});});await page.screenshot({path:path.join(__dirname,name+'.png')});if(name.startsWith('map-')||name.startsWith('more-'))await page.locator('.listing-search-panel').screenshot({path:path.join(__dirname,name+'-panel.png')});};
 try{
 await visit();const baseline=await page.evaluate(()=>JSON.stringify(publicState.properties));const baselineReads=reads;
 await check('Primary filters and closed defaults',async()=>{for(const id of ['listingPricePanel','listingMorePanel','listingMapPanel'])assert(!await page.locator('#'+id).isVisible());await page.locator('[data-listing-purpose="For Sale"]').click();assert.equal(await page.evaluate(()=>publicState.purpose),'For Sale');await select('listingTypeFilter','House');assert(await page.evaluate(()=>filteredListings().every(p=>p.purpose==='For Sale'&&p.property_type==='House')));await page.locator('[data-clear-all]').click();});
 await check('Price panel, currency validation and range',async()=>{await open('listingPricePanel');await page.locator('#listingMinPriceFilter').fill('100');await page.locator('#listingMinPriceFilter').press('Tab');assert.match(await page.locator('#listingFilterMessage').innerText(),/Choose ZMW or USD/);await select('listingCurrencyFilter','USD');await page.locator('#listingMaxPriceFilter').fill('1000000');await page.locator('#listingMaxPriceFilter').press('Tab');assert(await page.evaluate(()=>filteredListings().every(p=>p.currency_code==='USD'&&p.price>=100&&p.price<=1000000)));const url=page.url();await page.locator('[data-close-panel="listingPricePanel"]').click();assert.equal(page.url(),url);assert.equal(await page.locator('#listingPriceToggle').getAttribute('aria-expanded'),'false');await page.locator('[data-clear-all]').click();});
 await check('More filters open, close, Escape and combined filters',async()=>{const url=page.url();await open('listingMorePanel');assert.equal(page.url(),url);await select('listingCityFilter','lusaka');await select('listingAreaFilter','new-kasama');await select('listingBedroomsFilter','1');await select('listingStatusFilter','Active');await page.locator('#listingSearchInput').pressSequentially('New Kasama');assert.equal(await page.locator('#listingSearchInput').inputValue(),'New Kasama');assert(await page.evaluate(()=>filteredListings().every(p=>p.city_id&&p.bedrooms>=1&&p.status==='Active')));await page.locator('#listingSearchInput').press('Escape');assert(!await page.locator('#listingMorePanel').isVisible());assert.equal(await page.evaluate(()=>document.activeElement.id),'listingMoreToggle');assert.match(await page.locator('#listingMoreCount').innerText(),/5/);await page.locator('[data-clear-all]').click();});
 await check('All ten provinces, mouse/touch/Enter/Space and shared state',async()=>{await open('listingMapPanel');const slugs=await page.locator('#listingMapHolder path').evaluateAll(n=>n.map(p=>p.dataset.province));assert.equal(slugs.length,10);for(const slug of slugs){const p=page.locator('path[data-province="'+slug+'"]');await p.focus();await page.keyboard.press('Enter');await sync(slug);await p.focus();await page.keyboard.press('Space');await sync(slug);await select('listingProvinceFilter','all');await p.scrollIntoViewIfNeeded();const pt=await p.evaluate(p=>{const b=p.getBBox();for(let y=.1;y<1;y+=.1)for(let x=.1;x<1;x+=.1){const q=new DOMPoint(b.x+b.width*x,b.y+b.height*y);if(p.isPointInFill(q)){const s=q.matrixTransform(p.getScreenCTM());return {x:s.x,y:s.y};}}});await page.mouse.click(pt.x,pt.y);await sync(slug);await select('listingProvinceFilter','all');await page.touchscreen.tap(pt.x,pt.y);await sync(slug);}return slugs;});
 await check('Location to map, close/reopen persistence, All Zambia',async()=>{await select('listingProvinceFilter','southern');await sync('southern');const url=page.url();await page.locator('[data-close-panel="listingMapPanel"]').click();await open('listingMapPanel');assert.equal(page.url(),url);await sync('southern');await page.locator('[data-listing-purpose="For Sale"]').click();await page.locator('#listingAllZambia').click();await sync('all');assert.equal(await page.evaluate(()=>publicState.purpose),'For Sale');await page.locator('[data-clear-all]').click();});
 await check('Quick filters and chip removal preserve unrelated filters',async()=>{await select('listingProvinceFilter','lusaka');await page.locator('[data-listing-type="House"]').click();assert.equal(await page.locator('#listingTypeFilter').inputValue(),'House');await page.locator('[data-clear-control="listingProvinceFilter"]').click();await sync('all');assert.equal(await page.locator('#listingTypeFilter').inputValue(),'House');await page.locator('[data-listing-type="House"]').click();assert.equal(await page.locator('#listingTypeFilter').inputValue(),'all');});
 await check('No additional property requests during filtering',async()=>assert.equal(reads,baselineReads));
 await check('URL refresh, Back and Forward',async()=>{await visit('?province=lusaka&purpose=sale&type=house');await sync('lusaka');await page.reload();await page.waitForFunction(()=>publicState.listingsLoaded);await sync('lusaka');await select('listingProvinceFilter','southern');await select('listingProvinceFilter','copperbelt');await page.goBack();await sync('southern');await page.goBack();await sync('lusaka');await page.goForward();await sync('southern');assert.equal(await page.locator('#listingTypeFilter').inputValue(),'House');});
 await check('Null area slugs, MAER/Prime and LFV unchanged',async()=>{await visit();assert.equal(await page.evaluate(()=>JSON.stringify(publicState.properties)),baseline);const data=await page.evaluate(()=>publicState.properties.filter(p=>!p.area_slug).map(p=>({ref:p.reference_number,area:p.area,province:p.province_id,city:p.city_id})));await select('listingProvinceFilter','lusaka');await open('listingMorePanel');await select('listingAreaFilter','new-kasama');assert(await page.evaluate(()=>filteredListings().some(p=>p.reference_number==='LFV'&&!p.area_slug)));return data;});
 await check('Public visibility and sorting',async()=>{await visit();assert(await page.evaluate(()=>filteredListings().every(p=>['Active','Under Offer'].includes(p.status))));for(const sort of ['price-low','price-high','featured','newest']){await select('listingSortSelect',sort);assert.equal(await page.evaluate(()=>publicState.sort),sort);}return await count();});
 for(const width of (process.argv.includes('--checks')?[]:[1440,1280,1024,430,390,360]))await check('Responsive '+width,async()=>{await visit();await page.setViewportSize({width,height:1000});for(const [state,panel] of [['compact',null],['more','listingMorePanel'],['map','listingMapPanel']]){if(panel)await open(panel);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('.listing-search-panel').evaluate(el=>[...el.querySelectorAll('input,select,button')].filter(e=>e.getClientRects().length).every(e=>{const b=e.getBoundingClientRect();return b.left>=0&&b.right<=innerWidth&&b.height>=40;})));if(panel==='listingMapPanel'){assert(await page.locator('#listingMapHolder svg').evaluate(s=>{const v=s.viewBox.baseVal;return [...s.querySelectorAll('path')].every(p=>{const b=p.getBBox();return b.x>=v.x&&b.y>=v.y&&b.x+b.width<=v.x+v.width&&b.y+b.height<=v.y+v.height;});}));await select('listingProvinceFilter','lusaka');}await screenshot(state+'-'+width);}return 'No horizontal overflow; all controls ≥40px; geometry unclipped';});
 await check('Managing branch, result actions and map geometry',async()=>{await visit();await open('listingMorePanel');const branch=await page.locator('#listingBranchFilter option').nth(1).getAttribute('value');await select('listingBranchFilter',branch);assert(await page.evaluate(b=>filteredListings().every(p=>String(p.branch_id)===b),branch));await open('listingMapPanel');await select('listingProvinceFilter','lusaka');const url=page.url();await page.locator('#listingMapView').click();assert.equal(page.url(),url);assert(!await page.locator('#listingMapPanel').isVisible());assert.equal(await page.evaluate(()=>document.activeElement.id),'listingResultsHeading');await open('listingMorePanel');await page.locator('#listingShowProperties').click();assert(!await page.locator('#listingMorePanel').isVisible());await open('listingMapPanel');const original=JSON.parse(fs.readFileSync(path.join(root,'assets/zambia-provinces.json')));assert.deepEqual(await page.locator('#listingMapHolder path').evaluateAll(n=>n.map(p=>p.getAttribute('d'))),original.map(p=>p.d));});
 await check('Listings console errors',async()=>assert.deepEqual(errors,[]));
 await check('Property cards and detail navigation',async()=>{await page.setViewportSize({width:1440,height:1000});await visit('?province=lusaka');const row=await page.evaluate(()=>filteredListings()[0]);const card=page.locator('#listingsGrid .property-card').first();assert((await card.innerText()).includes(row.reference_number));const href=await card.evaluate(el=>el.getAttribute('href')||el.querySelector('a[href*="property-details"]').getAttribute('href'));await page.goto(base+'/'+href);await page.waitForFunction(id=>typeof detailsState!=='undefined'&&detailsState.property?.id===id,row.id,{timeout:45000});});
 await check('Detail navigation console',async()=>{assert(errors.every(e=>e.source&&new URL(e.source).pathname==='/favicon.ico'));return errors.length?'Existing property-detail favicon.ico returns 404; no JavaScript exceptions':'No errors';});
 }finally{fs.writeFileSync(path.join(__dirname,process.argv.includes('--checks')?'qa-followup.json':'qa-results.json'),JSON.stringify({results,errors},null,2));await browser.close();server.close();}
 if(results.some(r=>r.result==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});

